project_name: ara
before:
  hooks:
    - go generate -v ./...
dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
- id: ara
  env:
  - CGO_ENABLED=0
  main: main.go
  binary: ara
  ldflags:
  - -s -w
  - -X "github.com/bhojpur/ara/pkg/version.Version={{.Version}}-{{.ShortCommit}}
  - -X "github.com/bhojpur/ara/pkg/version.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
  - -X "github.com/bhojpur/ara/pkg/version.BuildCommit={{ .FullCommit }}"
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - 386
  ignore:
    - goos: linux
      goarch: 386
- id: arautl
  env:
  - CGO_ENABLED=0
  main: main-util.go
  binary: arautl
  flags:
    - -tags=util
  ldflags:
  - -s -w
  - -X "github.com/bhojpur/ara/pkg/version.Version={{.Version}}-{{.ShortCommit}}
  - -X "github.com/bhojpur/ara/pkg/version.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
  - -X "github.com/bhojpur/ara/pkg/version.BuildCommit={{ .FullCommit }}"
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - 386
  ignore:
    - goos: linux
      goarch: 386
archives:
- id: ara
  files:
  - "none*"
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  builds:
  - ara
- id: arautl
  files:
  - "none*"
  format: binary
  builds:
  - arautl
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
  header: |
    Bhojpur Ara breaks your usual Docker build by separating the layers. The idea is that
    this way we can avoid needless cache invalidation.
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/bhojpur/ara:{{ .Tag }}"
    extra_files:
    - README.md
